### ISSUE TITLE
如果下载失败，可以点击通知栏重新下载

### ISSUE THREAD

**Issue by magic0908** [BmobSnail/UpdateDemo#1]
遇到一个问题，就是如果下载的过程中失败了，在通知栏会提示下载失败，如果我想实现点击通知栏重新下载，这个怎么处理好？

**Comment by BmobSnail** [comment]
建议在点击通知栏的时候定向发个广播(Activity事先就注册好广播接收器)，接收到广播再重新下载

**Comment by magic0908** [comment]
也有可能用户在下载的时候点击了通知栏，这样就会同时下载两个了，需要判断当前是否正在下载或者下载失败，感觉这个也不是太好处理

**Comment by BmobSnail** [comment]
你仔细看一下demo，在handler已经分状态处理了。
下载的时候点击有下载的处理
完成了有完成的处理
失败自然也可以有单独的处理
