### ISSUE TITLE
mTextView = findViewById(R.id.main_textView);

### ISSUE THREAD

**Issue by coolBreezes** [BmobSnail/UpdateDemo#2]
mTextView = findViewById(R.id.main_textView);
博主，您好，在鸿洋的公众号上看到您的文章，想问下上面mainactivity中这段代码，为什么可以不需要类型转换呢

**Comment by numqin** [comment]
![image](https://user-images.githubusercontent.com/17881914/34657794-deae79b6-f464-11e7-961e-d74f728476b6.png)
